apiVersion: v1
kind: Pod
metadata:
  name: testpod
  #labels:
  #  testlabel: $(#environment["fmenv"].testout)$
spec:
  containers:
  imagePullSecrets:
  - name: registry-credentials
  - command:
    - sleep
    - "60000"
    image: busybox:latest
    imagePullPolicy: Always
    name: test 
